//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrenciesRatesParser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Acronim { get; set; }
        public string Country { get; set; }
    }
}
