//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrenciesRatesParser.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoinsRates> CoinsRates { get; set; }
        public virtual DbSet<DpdCities> DpdCities { get; set; }
        public virtual DbSet<Rates> Rates { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
    
        public virtual ObjectResult<spGetDPDCitiesTop10_Result> spGetDPDCitiesTop10(string text)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDPDCitiesTop10_Result>("spGetDPDCitiesTop10", textParameter);
        }
    
        public virtual ObjectResult<spGetTickerRates_Result> spGetTickerRates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetTickerRates_Result>("spGetTickerRates");
        }
    }
}
